#!/bin/bash
# Auto Script for Multi OS By Mtknetwork 2023
RED='\033[01;31m';
RESET='\033[0m';
GREEN='\033[01;32m';
WHITE='\033[01;37m';
YELLOW='\033[00;33m';

echo -e "                $RED Choose Your Category $RESET"
echo '                                                              
    ██████╗ ███████╗██╗  ██╗████████╗███████╗██████╗        
    ██╔══██╗██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗       
    ██║  ██║█████╗   ╚███╔╝    ██║   █████╗  ██████╔╝       
    ██║  ██║██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗       
    ██████╔╝███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║       
    ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝       
'     
PS3='Choose or Type a Plan: '
options=("$GREEN OVPN+SSH WEBSOCKET PREMIUM$RESET" "OVPN+SSH WEBSOCKET VIP" "OVPN+SSH WEBSOCKET PRIVATE" "HYSTERIA PURE" "SLOWDNS PURE" "SLOWDNS + SSH WEBSOCKET" "Quit")
select opt in "${options[@]}"; do
case "$opt,$REPLY" in
PREMIUM,*|*,PREMIUM) 
echo "";
echo -e "                 1)$GREEN OVPN+SSH WEBSOCKET PREMIUM Selected$RESET";
sleep 2s
clear
wget -O premium "https://raw.githubusercontent.com/DexterRepositories/Panel/main/premium"
chmod +x ~/premium && sed -i -e 's/\r$//' ~/premium && ./premium
echo "";
break ;;

VIP,*|*,VIP) 
echo "";
echo -e "                 2)$GREEN OVPN+SSH WEBSOCKET VIP Selected$RESET";
sleep 2s
clear
wget -O vip "https://raw.githubusercontent.com/DexterRepositories/Panel/main/vip"
chmod +x ~/vip && sed -i -e 's/\r$//' ~/vip && ./vip
echo "";
break ;;

PRIVATE,*|*,PRIVATE) 
echo "";
echo -e "                 3)$GREEN OVPN+SSH WEBSOCKET PRIVATE Selected$RESET";
sleep 2s
clear
wget -O private "https://raw.githubusercontent.com/DexterRepositories/Panel/main/private"
chmod +x ~/private && sed -i -e 's/\r$//' ~/private && ./private
echo "";
break ;;

HYSTERIA,*|*,HYSTERIA) 
echo "";
echo -e "                 4)$GREEN HYSTERIA PURE Selected$RESET";
sleep 2s
clear
wget -O udppure "https://github.com/DexterRepositories/Hysteria/blob/main/udppure"
chmod +x ~/udppure && sed -i -e 's/\r$//' ~/udppure && ./udppure
echo "";
break ;;

SLOWDNS,*|*,SLOWDNS) 
echo "";
echo -e "                 5)$GREEN SLOWDNS PURE Selected$RESET";
sleep 2s
clear
wget -O setup "https://raw.githubusercontent.com/DexterRepositories/Slowdns/main/installer/setup"
chmod +x ~/setup && sed -i -e 's/\r$//' ~/setup && ./setup
echo "";
break ;;

SLOWSSH,*|*,SLOWSSH) 
echo "";
echo -e "                 6)$GREEN SLOWDNS + SSH WEBSOCKET Selected$RESET";
sleep 2s
clear
wget -O install "https://raw.githubusercontent.com/DexterRepositories/Script/main/install"
chmod +x ~/install && sed -i -e 's/\r$//' ~/install && ./install
echo "";
break ;;

Quit,*|*,Quit) echo -e " $RED   Installation Cancelled!$RESET";
echo -e "                $RED   Rebuild your vps and correct the process.$RESET";
rm installer.sh
exit;
break ;; *)
echo -e "                $RED   Invalid: Just choose what you want$RESET";
esac
done
