#!/bin/bash
# Auto Script for Multi OS By Mtknetwork 2023
rm -rf MTK_AIO_INSTALLER*
RED='\033[01;31m';
RESET='\033[0m';
GREEN='\033[01;32m';
WHITE='\033[01;37m';
YELLOW='\033[00;33m';

echo -e "                $GREEN Choose Your Category $RESET"
echo '                                                            
    ██████╗ ███████╗██╗  ██╗████████╗███████╗██████╗        
    ██╔══██╗██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗       
    ██║  ██║█████╗   ╚███╔╝    ██║   █████╗  ██████╔╝       
    ██║  ██║██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗       
    ██████╔╝███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║       
    ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝       
'     
PS3='Choose script you want to run!!: '
options=("OVPN/SSH-WEBSOCKET-PREMIUM" "OVPN/SSH-WEBSOCKET-VIP" "OVPN/SSH-WEBSOCKET-PRIVATE" "Konnekz-Installer-Premium" "Konnekz-Installer-Vip" "Konnekz-Installer-Private" "PUREUDP1-MTK-EXTREME" "PUREUDP2-MTK-EXTREME" "SLOWDNS-PURE" "SLOWDNS/SSH-WEBSOCKET" "Cpanel3_MtkAio_Udpws" "Cpanel3_MtkExtreme_Udpws" "MTK-Vless-XrayCORE" "QUIT")
select opt in "${options[@]}"; do
case "$opt,$REPLY" in
OVPN/SSH-WEBSOCKET-PREMIUM,*|*,OVPN/SSH-WEBSOCKET-PREMIUM) 
echo "";
echo -e "                $GREEN 1) OVPN+SSH WEBSOCKET PREMIUM Selected$RESET";
sleep 2s
clear
wget -O premium "https://raw.githubusercontent.com/DexterRepositories/Panel/main/premium" chmod +x ~/premium && sed -i -e 's/\r$//' ~/premium && ./premium
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

OVPN/SSH-WEBSOCKET-VIP,*|*,OVPN/SSH-WEBSOCKET-VIP) 
echo "";
echo -e "                $GREEN 2) OVPN+SSH WEBSOCKET VIP Selected$RESET";
sleep 2s
clear
wget -O vip "https://raw.githubusercontent.com/DexterRepositories/Panel/main/vip" chmod +x ~/vip && sed -i -e 's/\r$//' ~/vip && ./vip
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

OVPN/SSH-WEBSOCKET-PRIVATE,*|*,OVPN/SSH-WEBSOCKET-PRIVATE) 
echo "";
echo -e "                $GREEN 3) OVPN+SSH WEBSOCKET PRIVATE Selected$RESET";
sleep 2s
clear
wget -O private "https://raw.githubusercontent.com/DexterRepositories/Panel/main/private" chmod +x ~/private && sed -i -e 's/\r$//' ~/private && ./private
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

Konnekz-Installer-Premium,*|*,Konnekz-Installer-Premium) 
echo "";
echo -e "                $GREEN 4) Konnekz Installer PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O konnekz_prem https://raw.githubusercontent.com/DexterRepositories/Panel/main/konnekz_prem; chmod +x konnekz_prem; setarch $(uname -m) -R /root/konnekz_prem
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

Konnekz-Installer-Vip,*|*,Konnekz-Installer-Vip) 
echo "";
echo -e "                $GREEN 5) Konnekz Installer VIP  Selected$RESET";
sleep 2s
clear
wget -O konnekz_vip https://raw.githubusercontent.com/DexterRepositories/Panel/main/konnekz_vip; chmod +x konnekz_vip; setarch $(uname -m) -R /root/konnekz_vip
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

Konnekz-Installer-Private,*|*,Konnekz-Installer-Private) 
echo "";
echo -e "                $GREEN 6) Konnekz Installer PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O konnekz_private https://raw.githubusercontent.com/DexterRepositories/Panel/main/konnekz_private; chmod +x konnekz_private; setarch $(uname -m) -R /root/konnekz_private
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

PUREUDP1-MTK-EXTREME,*|*,PUREUDP1-MTK-EXTREME) 
echo "";
echo -e "                $GREEN 7) PURE EXTREME UDP1 Selected$RESET";
sleep 2s
clear
wget -O udp "https://raw.githubusercontent.com/DexterRepositories/Hysteria/main/udp" && chmod +x udp && sed -i -e 's/\r$//' ~/udp && ./udp
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

PUREUDP2-MTK-EXTREME,*|*,PUREUDP2-MTK-EXTREME) 
echo "";
echo -e "                $GREEN 8) PURE EXTREME UDP2 Selected$RESET";
sleep 2s
clear
wget -O ubuntu20_udp "https://raw.githubusercontent.com/DexterRepositories/Script/main/ubuntu20_udp" && chmod +x ubuntu20_udp && sed -i -e 's/\r$//' ~/ubuntu20_udp && ./ubuntu20_udp
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

SLOWDNS-PURE,*|*,SLOWDNS-PURE) 
echo "";
echo -e "                $GREEN 9) SLOWDNS PURE Selected$RESET";
sleep 2s
clear
wget -O setup "https://raw.githubusercontent.com/DexterRepositories/Slowdns/main/installer/setup" && chmod +x setup && sed -i -e 's/\r$//' ~/setup && ./setup
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

SLOWDNS/SSH-WEBSOCKET,*|*,SLOWDNS/SSH-WEBSOCKET) 
echo "";
echo -e "                $GREEN 10) SLOWDNS+SSH WEBSOCKET Selected$RESET";
sleep 2s
clear
wget -O install "https://raw.githubusercontent.com/DexterRepositories/Script/main/install" && chmod +x install && sed -i -e 's/\r$//' ~/install && ./install
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

Cpanel3_MtkAio_Udpws,*|*,Cpanel3_MtkAio_Udpws) 
echo "";
echo -e "                $GREEN 11) CPANEL3 MTK AIO Selected$RESET";
sleep 2s
clear
wget -O cpanel3_mtkaio.x https://www.dropbox.com/s/4lru5as4r93q14n/cpanel3_mtkaio.x?dl=0; chmod +x cpanel3_mtkaio.x; setarch $(uname -m) -R /root/cpanel3_mtkaio.x
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

Cpanel3_MtkExtreme_Udpws,*|*,Cpanel3_MtkExtreme_Udpws) 
echo "";
echo -e "                $GREEN 12) CPANEL3 MTK EXTREME  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_extreme.x https://www.dropbox.com/s/7v8mvellszuhysv/cpanel3_extreme.x?dl=0; chmod +x cpanel3_extreme.x; setarch $(uname -m) -R /root/cpanel3_extreme.x
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

MTK-Vless-XrayCORE,*|*,MTK-Vless-XrayCORE) 
echo "";
echo -e "                $GREEN 13) MTK XRAY CORE VLESS  Selected$RESET";
sleep 2s
clear
wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/DexterRepositories/Panel/main/install.sh" && chmod +x install.sh && bash install.sh
echo "";
history -c
history -w
rm -rf MTK_AIO_INSTALLER
break ;;

QUIT,*|*,QUIT) 
echo -e " $RED   Installation Cancelled!$RESET";
exit;
break ;; *)
echo "";
echo -e "                $RED   Invalid: Just choose what you want$RESET";
esac
done
