#!/bin/bash
# Auto Script for Multi OS By Mtknetwork 2023
rm -rf MTK_INSTALLER_V24*
RED='\033[01;31m';
RESET='\033[0m';
GREEN='\033[01;32m';
WHITE='\033[01;37m';
YELLOW='\033[00;33m';

echo -e "                $GREEN Choose Your Category $RESET"
echo '                                                            
    ██████╗ ███████╗██╗  ██╗████████╗███████╗██████╗        
    ██╔══██╗██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗       
    ██║  ██║█████╗   ╚███╔╝    ██║   █████╗  ██████╔╝       
    ██║  ██║██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗       
    ██████╔╝███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║       
    ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝       
'     
PS3='Choose script you want to run!!: '
options=("OVPN/SSH-WEBSOCKET-PREMIUM" "OVPN/SSH-WEBSOCKET-VIP" "OVPN/SSH-WEBSOCKET-PRIVATE" "Konnekz-Installer-Premium" "Konnekz-Installer-Vip" "Konnekz-Installer-Private" "Cpanel3-Extreme-Premium" "Cpanel3-Extreme-Vip" "Cpanel3-Extreme-Private" "Cpanel3-Aio-Premium" "Cpanel3-Aio-Vip" "Cpanel3-Aio-Private" "Cpanel3Aio-Ubuntu20-Premium" "Cpanel3Aio-Ubuntu20-Vip" "Cpanel3Aio-Ubuntu20-Private" "PUREUDP1-MTK-EXTREME" "PUREUDP2-MTK-EXTREME" "SSH-WS-HYSTERIA" "SLOWDNS-PURE" "SLOWDNS/SSH-WEBSOCKET" "MTK-Vless-XrayCORE" "MTK-Aio-443" "QUIT")
select opt in "${options[@]}"; do
case "$opt,$REPLY" in
OVPN/SSH-WEBSOCKET-PREMIUM,*|*,OVPN/SSH-WEBSOCKET-PREMIUM) 
echo "";
echo -e "                $GREEN 1) OVPN+SSH WEBSOCKET PREMIUM Selected$RESET";
sleep 2s
clear
wget -O premium "https://raw.githubusercontent.com/DexterRepositories/Panel/main/premium" chmod +x ~/premium && sed -i -e 's/\r$//' ~/premium && ./premium
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

OVPN/SSH-WEBSOCKET-VIP,*|*,OVPN/SSH-WEBSOCKET-VIP) 
echo "";
echo -e "                $GREEN 2) OVPN+SSH WEBSOCKET VIP Selected$RESET";
sleep 2s
clear
wget -O vip "https://raw.githubusercontent.com/DexterRepositories/Panel/main/vip" chmod +x ~/vip && sed -i -e 's/\r$//' ~/vip && ./vip
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

OVPN/SSH-WEBSOCKET-PRIVATE,*|*,OVPN/SSH-WEBSOCKET-PRIVATE) 
echo "";
echo -e "                $GREEN 3) OVPN+SSH WEBSOCKET PRIVATE Selected$RESET";
sleep 2s
clear
wget -O private "https://raw.githubusercontent.com/DexterRepositories/Panel/main/private" chmod +x ~/private && sed -i -e 's/\r$//' ~/private && ./private
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Konnekz-Installer-Premium,*|*,Konnekz-Installer-Premium) 
echo "";
echo -e "                $GREEN 4) Konnekz Installer PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O konnekz_prem https://raw.githubusercontent.com/DexterRepositories/Panel/main/konnekz_prem; chmod +x konnekz_prem; setarch $(uname -m) -R /root/konnekz_prem
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Konnekz-Installer-Vip,*|*,Konnekz-Installer-Vip) 
echo "";
echo -e "                $GREEN 5) Konnekz Installer VIP  Selected$RESET";
sleep 2s
clear
wget -O konnekz_vip https://raw.githubusercontent.com/DexterRepositories/Panel/main/konnekz_vip; chmod +x konnekz_vip; setarch $(uname -m) -R /root/konnekz_vip
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Konnekz-Installer-Private,*|*,Konnekz-Installer-Private) 
echo "";
echo -e "                $GREEN 6) Konnekz Installer PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O konnekz_private https://raw.githubusercontent.com/DexterRepositories/Panel/main/konnekz_private; chmod +x konnekz_private; setarch $(uname -m) -R /root/konnekz_private
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Extreme-Premium,*|*,Cpanel3-Extreme-Premium) 
echo "";
echo -e "                $GREEN 7) Cpanel3 Extreme PRIVATE PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O cpanel3-extreme_premium https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3-extreme_premium; chmod +x cpanel3-extreme_premium; setarch $(uname -m) -R /root/cpanel3-extreme_premium
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Extreme-Vip,*|*,Cpanel3-Extreme-Vip) 
echo "";
echo -e "                $GREEN 8) Cpanel3 Extreme PRIVATE VIP  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_extreme_vip https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3_extreme_vip; chmod +x cpanel3_extreme_vip; setarch $(uname -m) -R /root/cpanel3_extreme_vip
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Extreme-Private,*|*,Cpanel3-Extreme-Private) 
echo "";
echo -e "                $GREEN 9) Cpanel3 Extreme PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_extreme_private https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3_extreme_private; chmod +x cpanel3_extreme_private; setarch $(uname -m) -R /root/cpanel3_extreme_private
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Aio-Premium,*|*,Cpanel3-Aio-Premium) 
echo "";
echo -e "                $GREEN 10) Cpanel3 AIO PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_aio_premium https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3_aio_premium; chmod +x cpanel3_aio_premium; setarch $(uname -m) -R /root/cpanel3_aio_premium
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Aio-Vip,*|*,Cpanel3-Aio-Vip) 
echo "";
echo -e "                $GREEN 11) Cpanel3 AIO VIP  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_aio_vip https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3_aio_vip; chmod +x cpanel3_aio_vip; setarch $(uname -m) -R /root/cpanel3_aio_vip
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Aio-Private,*|*,Cpanel3-Aio-Private) 
echo "";
echo -e "                $GREEN 12) Cpanel3 AIO PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_aio_private https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3_aio_private; chmod +x cpanel3_aio_private; setarch $(uname -m) -R /root/cpanel3_aio_private
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3Aio-Ubuntu20-Premium,*|*,Cpanel3Aio-Ubuntu20-Premium) 
echo "";
echo -e "                $GREEN 13) Cpanel3 AIO Ubuntu20  Selected$RESET";
sleep 2s
clear
wget -O cpanel3aio_ubuntu20_premium https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3aio_ubuntu20_premium; chmod +x cpanel3aio_ubuntu20_premium; setarch $(uname -m) -R /root/cpanel3aio_ubuntu20_premium
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3Aio-Ubuntu20-Vip,*|*,Cpanel3Aio-Ubuntu20-Vip) 
echo "";
echo -e "                $GREEN 14) Cpanel3 AIO Ubuntu20  Selected$RESET";
sleep 2s
clear
wget -O cpanel3aio_ubuntu20_vip https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3aio_ubuntu20_vip; chmod +x cpanel3aio_ubuntu20_vip; setarch $(uname -m) -R /root/cpanel3aio_ubuntu20_vip
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3Aio-Ubuntu20-Private,*|*,Cpanel3Aio-Ubuntu20-Private) 
echo "";
echo -e "                $GREEN 15) Cpanel3 AIO Ubuntu20  Selected$RESET";
sleep 2s
clear
wget -O cpanel3aio_ubuntu20_private https://raw.githubusercontent.com/DexterRepositories/Panel/main/cpanel3aio_ubuntu20_private; chmod +x cpanel3aio_ubuntu20_private; setarch $(uname -m) -R /root/cpanel3aio_ubuntu20_private
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

PUREUDP1-MTK-EXTREME,*|*,PUREUDP1-MTK-EXTREME) 
echo "";
echo -e "                $GREEN 16) PURE EXTREME UDP1 Selected$RESET";
sleep 2s
clear
wget -O udp "https://raw.githubusercontent.com/DexterRepositories/Hysteria/main/udp" && chmod +x udp && sed -i -e 's/\r$//' ~/udp && ./udp
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

PUREUDP2-MTK-EXTREME,*|*,PUREUDP2-MTK-EXTREME) 
echo "";
echo -e "                $GREEN 17) PURE EXTREME UDP2 Selected$RESET";
sleep 2s
clear
wget -O ubuntu20_udp "https://raw.githubusercontent.com/DexterRepositories/Script/main/ubuntu20_udp" && chmod +x ubuntu20_udp && sed -i -e 's/\r$//' ~/ubuntu20_udp && ./ubuntu20_udp
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

SSH-WS-HYSTERIA,*|*,SSH-WS-HYSTERIA) 
echo "";
echo -e "                $GREEN 18) PURE EXTREME UDP2 Selected$RESET";
sleep 2s
clear
wget -O sshws_hysteria "https://raw.githubusercontent.com/DexterRepositories/Script/main/sshws_hysteria" && chmod +x sshws_hysteria && sed -i -e 's/\r$//' ~/sshws_hysteria && ./sshws_hysteria
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

SLOWDNS-PURE,*|*,SLOWDNS-PURE) 
echo "";
echo -e "                $GREEN 19) SLOWDNS PURE Selected$RESET";
sleep 2s
clear
wget -O setup "https://raw.githubusercontent.com/DexterRepositories/Slowdns/main/installer/setup" && chmod +x setup && sed -i -e 's/\r$//' ~/setup && ./setup
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

SLOWDNS/SSH-WEBSOCKET,*|*,SLOWDNS/SSH-WEBSOCKET) 
echo "";
echo -e "                $GREEN 20) SLOWDNS+SSH WEBSOCKET Selected$RESET";
sleep 2s
clear
wget -O install "https://raw.githubusercontent.com/DexterRepositories/Script/main/install" && chmod +x install && sed -i -e 's/\r$//' ~/install && ./install
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-Vless-XrayCORE,*|*,MTK-Vless-XrayCORE) 
echo "";
echo -e "                $GREEN 21) MTK XRAY CORE VLESS  Selected$RESET";
sleep 2s
clear
wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/DexterRepositories/Panel/main/install.sh" && chmod +x install.sh && bash install.sh
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-Aio-443*|*,MTK-Aio-443) 
echo "";
echo -e "                $GREEN 22) PROMO APP SCRIPT  Selected$RESET";
sleep 2s
clear
wget -O aio_443 "https://raw.githubusercontent.com/DexterRepositories/Panel/main/aio_443" && chmod +x aio_443 && sed -i -e 's/\r$//' ~/aio_443 && ./aio_443
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

QUIT,*|*,QUIT) 
echo -e " $RED   Installation Cancelled!$RESET";
exit;
break ;; *)
echo "";
echo -e "                $RED   Invalid: Just choose what you want$RESET";
esac
done
