#!/bin/bash
# Zivpn UDP Module installer
# Creator Zahid Islam
rm -rf udp_zivpn_mtk*

echo -e "Updating server"
apt-get update
apt-get upgrade -y
apt install ufw

systemctl stop hysteria-server.service

wget -N --no-check-certificate -q -O ~/install_server.sh https://raw.githubusercontent.com/DexterRepositories/Hysteria/main/install_server.sh; chmod +x ~/install_server.sh; ./install_server.sh

mkdir /etc/hysteria
wget https://raw.githubusercontent.com/DexterRepositories/Panel/main/zivpn/obfs_extreme -O /etc/hysteria/config.json

echo "Generating cert files:"
openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=California/L=Los Angeles/O=Example Corp/OU=IT Department/CN=zivpn" -keyout "/etc/hysteria/zivpn.key" -out "/etc/hysteria/zivpn.crt"

sysctl -w net.core.rmem_max=16777216
sysctl -w net.core.wmem_max=16777216


if [ -n "$input_config" ]; then
    IFS=',' read -r -a config <<< "$input_config"
    if [ ${#config[@]} -eq 1 ]; then
        config+=(${config[0]})
    fi
else
    config=("mtkvpn")
fi

new_config_str="\"config\": [$(printf "\"%s\"," "${config[@]}" | sed 's/,$//')]"

sed -i -E "s/\"config\": ?\[[[:space:]]*\"zi\"[[:space:]]*\]/${new_config_str}/g" /etc/hysteria/config.json

systemctl enable hysteria-server.service
systemctl start hysteria-server.service
iptables -t nat -A PREROUTING -i $(ip -4 route ls|grep default|grep -Po '(?<=dev )(\S+)'|head -1) -p udp --dport 20000:50000 -j DNAT --to-destination :5666
ufw allow 20000:50000/udp
ufw allow 5666/udp
rm -rf udp_zivpn_mtk
ln -sf /dev/null ~/.bash_history
echo -e "Installed"
