#!/bin/bash
# Auto Script for Multi OS By Mtknetwork 2023
rm -rf MTK_INSTALLER_V24*
RED='\033[01;31m';
RESET='\033[0m';
GREEN='\033[01;32m';
WHITE='\033[01;37m';
YELLOW='\033[00;33m';

echo -e "                $GREEN Choose Your Category $RESET"
echo '                                                            
    ██████╗ ███████╗██╗  ██╗████████╗███████╗██████╗        
    ██╔══██╗██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗       
    ██║  ██║█████╗   ╚███╔╝    ██║   █████╗  ██████╔╝       
    ██║  ██║██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗       
    ██████╔╝███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║       
    ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝       
'     
PS3='Choose script you want to run!!: '
options=("Konnekz-Installer-Premium" "Konnekz-Installer-Vip" "Konnekz-Installer-Private" "Cpanel3-Extreme-Premium" "Cpanel3-Extreme-Vip" "Cpanel3-Extreme-Private" "Cpanel3-Aio-Premium" "Cpanel3-Aio-Vip" "Cpanel3-Aio-Private" "UdpPromoFybe-443-Premium" "UdpPromoFybe-443-Vip" "UdpPromoFybe-443-Private" "MTK-PROMO-PREMIUM" "MTK-PROMO-VIP" "MTK-PROMO-PRIVATE" "PUREUDP-MTK-EXTREME" "SSH-WS-HYSTERIA" "SLOWDNS-PURE" "SLOWDNS/SSH-WEBSOCKET" "MTK-Vless-XrayCORE" "MTK-AWS-PREMIUM" "MTK-AWS-VIP" "MTK-AWS-PRIVATE" "UDP-CUSTOM-OBFS" "QUIT")
select opt in "${options[@]}"; do
case "$opt,$REPLY" in

Konnekz-Installer-Premium,*|*,Konnekz-Installer-Premium) 
echo "";
echo -e "                $GREEN 1) Konnekz Installer PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O konnekz_prem.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/KONNEKZ-INSTALLER/konnekz_prem.x; chmod +x konnekz_prem.x; setarch $(uname -m) -R /root/konnekz_prem.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Konnekz-Installer-Vip,*|*,Konnekz-Installer-Vip) 
echo "";
echo -e "                $GREEN 2) Konnekz Installer VIP  Selected$RESET";
sleep 2s
clear
wget -O konnekz_vip.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/KONNEKZ-INSTALLER/konnekz_vip.x; chmod +x konnekz_vip.x; setarch $(uname -m) -R /root/konnekz_vip.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Konnekz-Installer-Private,*|*,Konnekz-Installer-Private) 
echo "";
echo -e "                $GREEN 3) Konnekz Installer PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O konnekz_private.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/KONNEKZ-INSTALLER/konnekz_private.x; chmod +x konnekz_private.x; setarch $(uname -m) -R /root/konnekz_private.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Extreme-Premium,*|*,Cpanel3-Extreme-Premium) 
echo "";
echo -e "                $GREEN 4) Cpanel3 Extreme PRIVATE PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_extreme_premium.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/CPANEL3-EXTREME-DEBIAN/cpanel3_extreme_premium.x; chmod +x cpanel3_extreme_premium.x; setarch $(uname -m) -R /root/cpanel3_extreme_premium.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Extreme-Vip,*|*,Cpanel3-Extreme-Vip) 
echo "";
echo -e "                $GREEN 5) Cpanel3 Extreme PRIVATE VIP  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_extreme_vip.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/CPANEL3-EXTREME-DEBIAN/cpanel3_extreme_vip.x; chmod +x cpanel3_extreme_vip.x; setarch $(uname -m) -R /root/cpanel3_extreme_vip.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Extreme-Private,*|*,Cpanel3-Extreme-Private) 
echo "";
echo -e "                $GREEN 6) Cpanel3 Extreme PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_extreme_private.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/CPANEL3-EXTREME-DEBIAN/cpanel3_extreme_private.x; chmod +x cpanel3_extreme_private.x; setarch $(uname -m) -R /root/cpanel3_extreme_private.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Aio-Premium,*|*,Cpanel3-Aio-Premium) 
echo "";
echo -e "                $GREEN 7) Cpanel3 AIO PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_aio_premium.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/CPANEL3-AIO-DEBIAN/cpanel3_aio_premium.x; chmod +x cpanel3_aio_premium.x; setarch $(uname -m) -R /root/cpanel3_aio_premium.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Aio-Vip,*|*,Cpanel3-Aio-Vip) 
echo "";
echo -e "                $GREEN 8) Cpanel3 AIO VIP  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_aio_vip.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/CPANEL3-AIO-DEBIAN/cpanel3_aio_vip.x; chmod +x cpanel3_aio_vip.x; setarch $(uname -m) -R /root/cpanel3_aio_vip.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

Cpanel3-Aio-Private,*|*,Cpanel3-Aio-Private) 
echo "";
echo -e "                $GREEN 9) Cpanel3 AIO PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O cpanel3_aio_private.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/CPANEL3-AIO-DEBIAN/cpanel3_aio_private.x; chmod +x cpanel3_aio_private.x; setarch $(uname -m) -R /root/cpanel3_aio_private.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

UdpPromoFybe-443-Premium,*|*,UdpPromoFybee-443-Premium) 
echo "";
echo -e "                $GREEN 10) MTK PROMO 443 Premium  Selected$RESET";
sleep 2s
clear
wget -O aio_443_premium.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/MTK-AIO-PROMO-443/aio_443_premium.x; chmod +x aio_443_premium.x; setarch $(uname -m) -R /root/aio_443_premium.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

UdpPromoFybe-443-Vip,*|*,UdpPromoFybe-443-Vip) 
echo "";
echo -e "                $GREEN 11) MTK PROMO 443 Vip  Selected$RESET";
sleep 2s
clear
wget -O aio_443_vipx https://raw.githubusercontent.com/DexterRepositories/Panel/main/MTK-AIO-PROMO-443/aio_443_vip.x; chmod +x aio_443_vip.x; setarch $(uname -m) -R /root/aio_443_vip.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

UdpPromoFybe-443-Private,*|*,UdpPromoFybe-443-Private) 
echo "";
echo -e "                $GREEN 12) MTK PROMO 443 Private  Selected$RESET";
sleep 2s
clear
wget -O aio_443_private.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/MTK-AIO-PROMO-443/aio_443_private.x; chmod +x aio_443_private.x; setarch $(uname -m) -R /root/aio_443_private.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-PROMO-PREMIUM*|*,MTK-PROMO-PREMIUM) 
echo "";
echo -e "                $GREEN 13) MTK PROMO APP PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O strongcert_ovpn_prem.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/SCRIPT-PROMO-APPS/strongcert_ovpn_prem.x; chmod +x strongcert_ovpn_prem.x; setarch $(uname -m) -R /root/strongcert_ovpn_prem.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-PROMO-VIP*|*,MTK-PROMO-VIP) 
echo "";
echo -e "                $GREEN 14) MTK PROMO APP VIP  Selected$RESET";
sleep 2s
clear
wget -O strongcert_ovpn_vip.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/SCRIPT-PROMO-APPS/strongcert_ovpn_vip.x; chmod +x strongcert_ovpn_vip.x; setarch $(uname -m) -R /root/strongcert_vip_prem.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-PROMO-PRIVATE*|*,MTK-PROMO-PRIVATE) 
echo "";
echo -e "                $GREEN 15) MTK PROMO APP PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O strongcert_ovpn_private.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/SCRIPT-PROMO-APPS/strongcert_ovpn_private.x; chmod +x strongcert_ovpn_private.x; setarch $(uname -m) -R /root/strongcert_ovpn_private.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

PUREUDP-MTK-EXTREME,*|*,PUREUDP-MTK-EXTREME) 
echo "";
echo -e "                $GREEN 16) PURE EXTREME UDP Selected$RESET";
sleep 2s
clear
wget -O DeBuntu_Udp.x https://raw.githubusercontent.com/DexterRepositories/Script/main/DeBuntu_Udp.x; chmod +x DeBuntu_Udp.x; setarch $(uname -m) -R /root/DeBuntu_Udp.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

SSH-WS-HYSTERIA,*|*,SSH-WS-HYSTERIA) 
echo "";
echo -e "                $GREEN 17) SSH/WS + HYSTERIA Selected$RESET";
sleep 2s
clear
wget -O sshws_hysteria.x https://raw.githubusercontent.com/DexterRepositories/Script/main/sshws_hysteria.x; chmod +x sshws_hysteria.x; setarch $(uname -m) -R /root/sshws_hysteria.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

SLOWDNS-PURE,*|*,SLOWDNS-PURE) 
echo "";
echo -e "                $GREEN 18) SLOWDNS PURE Selected$RESET";
sleep 2s
clear
wget -O setup.x https://raw.githubusercontent.com/DexterRepositories/Slowdns/main/installer/setup.x; chmod +x setup.x; setarch $(uname -m) -R /root/setup.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

SLOWDNS/SSH-WEBSOCKET,*|*,SLOWDNS/SSH-WEBSOCKET) 
echo "";
echo -e "                $GREEN 19) SLOWDNS + SSH/WEBSOCKET Selected$RESET";
sleep 2s
clear
wget -O install.x https://raw.githubusercontent.com/DexterRepositories/Script/main/install.x; chmod +x install.x; setarch $(uname -m) -R /root/install.x
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-Vless-XrayCORE,*|*,MTK-Vless-XrayCORE) 
echo "";
echo -e "                $GREEN 20) MTK XRAY CORE VLESS  Selected$RESET";
sleep 2s
clear
wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/DexterRepositories/Panel/main/install.sh" && chmod +x install.sh && bash install.sh
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-AWS-PREMIUM*|*,MTK-AWS-PREMIUM) 
echo "";
echo -e "                $GREEN 21) MTK AWS PREMIUM  Selected$RESET";
sleep 2s
clear
wget -O amazonaws-premium-aio.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/AWS-LIGHTSAIL/amazonaws-premium-aio.x; chmod +x amazonaws-premium-aio.x; setarch $(uname -m) -R /root/amazonaws-premium-aio.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-AWS-VIP*|*,MTK-AWS-VIP) 
echo "";
echo -e "                $GREEN 22) MTK AWS VIP  Selected$RESET";
sleep 2s
clear
wget -O amazonaws-vip-aio.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/AWS-LIGHTSAIL/amazonaws-vip-aio.x; chmod +x amazonaws-vip-aio.x; setarch $(uname -m) -R /root/amazonaws-vip-aio.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

MTK-AWS-PRIVATE*|*,MTK-AWS-PRIVATE) 
echo "";
echo -e "                $GREEN 23) MTK AWS PRIVATE  Selected$RESET";
sleep 2s
clear
wget -O amazonaws-private-aio.x https://raw.githubusercontent.com/DexterRepositories/Panel/main/AWS-LIGHTSAIL/amazonaws-private-aio.x; chmod +x amazonaws-private-aio.x; setarch $(uname -m) -R /root/amazonaws-private-aio.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

UDP-CUSTOM-OBFS*|*,UDP-CUSTOM-OBFS) 
echo "";
echo -e "                $GREEN 24) UDP CUSTOM OBFS  Selected$RESET";
sleep 2s
clear
wget -O DeBuntu_Udp.x https://raw.githubusercontent.com/DexterRepositories/Script/main/DeBuntu_Udp.x; chmod +x DeBuntu_Udp.x; setarch $(uname -m) -R /root/DeBuntu_Udp.x
echo "";
history -c
history -w
rm -rf MTK_INSTALLER_V24
break ;;

QUIT,*|*,QUIT) 
echo -e " $RED   Installation Cancelled!$RESET";
exit;
break ;; *)
echo "";
echo -e "                $RED   Invalid: Just choose what you want$RESET";
esac
done
